name: Test My Hello-World Action

on:
    schedule:
        - cron: "0 0 * * *" # Runs at midnight every day
        # - cron: "0 * * * *" # run every hour
        # - cron: "*/30 * * * *" # Every 30 minutes
        # 0 - Run at the top of every hour (minute 0)
        # * - Every hour
        # * - Every day of the month
        # * - Every month
        # * - Every day of the week
    push:
        branches:
            - main
            - feature/*

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run python action
              uses: ./ 
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
