name: Test My Hello-World Action

on:
    push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run python action
              uses: ./ 
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
